### ISSUE TITLE
improving UI of login and register page

### ISSUE THREAD

**Issue by Komal73** [kailashchoudhary11/steganohide#22]
The UI is the basic HTML structure. I want to enhance the UI for better user interaction.

**Comment by Komal73** [comment]
@kailashchoudhary11 Kindly assign me the issue under codepeak 2023

**Comment by kailashchoudhary11** [comment]
Hi, do you have any designs in mind?

**Comment by Komal73** [comment]
The way 'hide' page is designed as it is according to the website's UI.

**Comment by kailashchoudhary11** [comment]
> The way 'hide' page is designed as it is according to the website's UI.

Okay, you can create a pr once done.

**Comment by Komal73** [comment]
okay.

**Comment by Albert-2** [comment]
hey @Komal73..... 
you still working on this issue if not then @kailashchoudhary11 please assign me the same i'll contribute...
THANK YOU FOR CONSIDERING...... :)

**Comment by kailashchoudhary11** [comment]
Hey @Albert-2 I think komal is already working on the issue.
